select * from gfg.products;

# 1. Finding the top 5 most expensive brands
# 2. Finding the top 5 most expensive brands with average rating more than 4.5
# 3. Finding the top 5 most expensive brands with average rating more than 4.5 and price less than 5000
# 4. Finding the top 5 most sold brands with average rating more than 4.5 and price less than 5000
# 5. Finding the top 5 most sold brands with average rating more than 4.5 and price between 2000 and 5000
# 6. Finding the top 5 most sold brands in price range 0 - 1000
# 7. Finding the top 5 most sold brands in price range 1000 - 2500
# 8. Finding the top 5 most sold brands in price range 2500 - 5000
# 9. Finding the top 5 most sold brands in price range 5000 - 10000
# 10. Finding the top 5 most sold brands in price more than 10000
# 11. Top 5 brands with maximum products sold
# 12. Top 5 brands with maximum revenue generated
# 13. List the name of brands which has generated more than 100 million in revenue
# 14. Top 10 prodcut categories with most number of products sold
# 15. List the name of brands which has generated more than 100 million in revenue
# 16. Top 5 best-selling prodcut categories under Rs 1000
# 17. Top 5 best-selling prodcut categories with price between 1000 - 2500
# 18. Top 5 best-selling prodcut categories with price between 2500 - 5000
# 19. Top 5 best-selling prodcut categories with price between 5000 - 10000
# 20. Top 5 best-selling prodcut categories with price more than 10000
# 21. Top 5 bestselling watch brands price between 2500-5000
# 22. Best-selling product of the year
# 22. Most revenue generated by any product
# 23. Best-selling watch of the year
# 24. Best-selling watch of the year between price 2500 and 5000
# 25. Best-selling tshirt of the year